console.log("==========ASSIGNMENT 02==========");
console.log("++++++++ TASK 01 ++++++++\n");
var bankName;
console.log("Bank Name:",bankName, "DataType:",typeof bankName);
var bankName = "SBI Bank";
console.log("Bank Name:",bankName, "DataType:",typeof bankName,"\n");
console.log("++++++++ TASK 02 ++++++++");
var marks = '90%';
console.log("Marks:-",marks,"DataType:",typeof marks,"\n");
console.log("+++++++ TASK 03 ++++++++");
var isWorking;
console.log("Working: ",isWorking, "DataType:",typeof isWorking);
var isWorking = true;
console.log("Working: ",isWorking, "DataType:",typeof isWorking,"\n");
console.log("++++++++ TASK 04-a ++++++++");
var totalCount = "Hundred and Seven";
console.log("Total Count: ",totalCount, "DataType:",typeof totalCount);
console.log("++++++++ TASK 04-b ++++++++");
var totalCount = 105;
console.log("Total Count: ",totalCount, "DataType:",typeof totalCount);
